jenkins

diff --git a/ci/Jenkinsfile b/ci/Jenkinsfile
--- a/ci/Jenkinsfile
+++ b/ci/Jenkinsfile
@@ -42,27 +42,28 @@ pipeline {
 
         stage('Unit Test') {
             steps {
-                script {
-                    docker.withRegistry("https://${DOCKER_REGISTRY}", "${CREDENTIAL_ID}"){
-                        // to use buildImage with host's network stack
-                        def buildImage = docker.image("${BUILD_IMAGE}")
-                        buildImage.withRun("") { c ->
-                            docker.image("mongo:4.4").run("-p 27017:27017")
-                            buildImage.inside("--net host") {
-                                sh """
-                                echo 'Running unit tests'
-                                # Disable exit on non 0
-                                set +e
-                                cd _build
-                                # pipe to true to prevent exit failure
-                                ctest -T Test --no-compress-output --extra-verbose || true
-                                """
-                            }
-                            sh "docker logs ${c.id} > integration-test.log"
-                            archive 'integration-test.log'
+              script {
+                def buildImage = docker.image("${BUILD_IMAGE}")
+                docker.withRegistry("https://${DOCKER_REGISTRY}", "${CREDENTIAL_ID}"){
+                    docker.image("mongo:4.4").run("-p 27017:27017") // mongo is required for unit test
+                    // to use buildImage with host's network stack
+                    buildImage.withRun("") { c ->
+                        buildImage.inside("--net host") {
+                            sh """
+                            echo 'Running unit tests'
+                            # Disable exit on non 0
+                            set +e
+                            cd _build
+                            # pipe to true to prevent exit failure
+                            ctest -T Test --no-compress-output || true
+                            """
                         }
+                        sh "docker logs ${c.id} > integration-test.log"
+                        archive 'integration-test.log'
                     }
+
                 }
+              }
             }
             post {
                 always {
